---
title: "Talks by Presenter's First Name"
output: 
  github_document
---
```{r fn_def, echo = FALSE, }
suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(knitr)
  library(glue)
  library(humaniformat)
  library(stringr)
  library(lubridate)
})

all_talks = read_rds('scrape/afs_2024_talk_info.rds') #  #unnest(session_info) |> 
      # mutate(date = as_date(start_time)) |> 
# by_author =  all_talks |> select(author, affiliation, times, numeric_date, session_room, title, session_name,session_id, abstract_id) |> 
#   mutate(author = str_remove(author, ',.+') |> str_remove_all(fixed('(')) |> str_remove_all(fixed(')')),
#          first = first_name(author), last = last_name(author) |> str_to_title(),
#          date = numeric_date |> strftime('%a, %m/%d'),
#          mdl = middle_name(author), mdl = if_else(is.na(mdl), '', paste0(' ', mdl)), 
#          author_last = glue("{last}, {first}{mdl}"),
#          session_url = glue('https://www.xcdsystem.com/afs/program/y7rKVr9/index.cfm?pgid=1485&sid={str_remove(session_id, "Sess")}'),
#          title_url = glue('https://www.xcdsystem.com/afs/program/y7rKVr9/index.cfm?pgid=1485&sid={str_remove(session_id, "Sess")}&abid={abstract_id}'),
#          title = glue("[{title}]({title_url})"),
#          session = glue("[{session_name}]({session_url})"))

by_name = all_talks |> 
  mutate(author_sort = author |> str_remove_all('"') |> str_to_sentence()) |> 
  arrange(author_sort, title) |> 
  select(author, author_sort, affiliation, title = title_md,  #`start time` = start_time, `end time` = end_time,
         date = print_date,time = short_times, room = session_room, session = session_md) |> rename_with(str_to_title) |> 
  filter(!is.na(Author))

nested_name = by_name |> mutate(letter = Author_sort|> substr(1, 1)) |> 
  select(-Author_sort) |> 
  group_by(letter) |> nest() |> ungroup()

make_by_letter_section = \(letter, data, level = 1) {
  headline = c(rep('#', level), ' ', letter, '\n') |> paste(sep = '')
  cat(headline)
  data |> kable(escape = TRUE) |> print()
}
```

For quick navigation, click the <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path d="M5.75 2.5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5Zm0 5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5Zm0 5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5ZM2 14a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm1-6a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 4a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg> icon in the upper-right of the page.


```{r, results = 'asis', echo = FALSE}
pwalk(nested_name, make_by_letter_section)
```
